# fly.toml app configuration file generated for hc on 2024-03-24T23:52:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hc'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = "hc_data"
  destination = "/data"
  initial_size = "1gb"

[[services]]
  protocol = 'tcp'
  internal_port = 8080

[[services.ports]]
    port = 80
    handlers = ['http']

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
